### ISSUE TITLE
Type definition file is missing from the npm package 

### ISSUE THREAD

**Issue by Chandu** [RennCheung/codemirror-editor-vue3#1]
I have installed this package to my typescript project, but found that the type definition file is missing from the npm package.
It would be great if the type definitions are included in the npm package.

![image](https://user-images.githubusercontent.com/261027/135135788-a91d31f1-c9a0-4d52-a341-258a0a5ec8cb.png)

**Comment by RennCheung** [comment]
Before I found this plugin based on my JavaScript project. This is a good suggestion. The recent work is busy, I will consider supporting this function in October.

**Comment by RennCheung** [comment]
2.0.x already supports ts
https://renncheung.github.io/codemirror-editor-vue3/tsSupport/index.html
