### ISSUE TITLE
merge 模式报错

### ISSUE THREAD

**Issue by songyang1996** [RennCheung/codemirror-editor-vue3#14]
https://renncheung.github.io/codemirror-editor-vue3/merge/index.html
官方文档中存在报错，编辑器渲染为空。

app.630317b7.js:1 TypeError: Cannot read properties of undefined (reading 'appendChild')
    at new E.MergeView (index.0db5470d.js:24:15082)

------------------
通过 sourcemap
看起来是
codemirror/addon/merge/merge.js 542行 下的 MergeView = CodeMirror.MergeView = function(node, options) {}
参数node为none。
574行 var wrapElt = this.wrap = node.appendChild(elt("div", wrap, "CodeMirror-merge CodeMirror-merge-" + panes + "pane"));
导致的空指针报错

**Comment by RennCheung** [comment]
最新版本已解决。

之后有空会考虑加上单元测试。
