### ISSUE TITLE
placeholder设置响应式数据，视图上不变化

### ISSUE THREAD

**Issue by xclss99** [RennCheung/codemirror-editor-vue3#15]
### Describe the bug

我把placeholder当做属性传进来，子组件中我用watch监听打印出来确实变化了，但是视图上却没变化，
<code-mirror
      v-model:value="code"
      :options="options"
      :placeholder="placeholder"
      :height="300"
      @change="onChange"
 />
const props = defineProps({
  code: {
    default: '',
    type: String
  },
  placeholder: {
    default: '',
    type: String
  }
})
const code = toRef(props, 'code')
const placeholder = toRef(props, 'placeholder')
watch(placeholder, function (newVal, oldVal) {
  console.log(newVal, oldVal)
})
我改成直接用响应式数据不用props，也不行

### Validations

- [X] Read the [docs](https://renncheung.github.io/codemirror-editor-vue3/index.html).
- [X] Check that there isn't [already an issue](https://github.com/RennCheung/codemirror-editor-vue3/issues) that reports the same bug to avoid creating a duplicate.

**Comment by RennCheung** [comment]
fixed
https://github.com/RennCheung/codemirror-editor-vue3/blob/main/CHANGELOG.md
