### ISSUE TITLE
[Question] Codemirror Extensions

### ISSUE THREAD

**Issue by abreumatheus** [RennCheung/codemirror-editor-vue3#16]
Hi. thank you for your great work on this package.

I would like to know if it's possible to use codemirror extesions on this project, and how to do it.
I would like to use the extension [codemirror-vscode-keymap](https://github.com/replit/codemirror-vscode-keymap).

**Comment by RennCheung** [comment]
This library is made based on Codemirror 5.x, and [codemirror-vscode-keymap] (https://github.com/replit/codemirror-vscode-keymap) is Codemirror, which should be unable to be compatible.
