### ISSUE TITLE
JS style injection doesn't work well with web components or customisation

### ISSUE THREAD

**Issue by Buroni** [RennCheung/codemirror-editor-vue3#17]
### Describe the bug

Hi, firstly thanks for the useful library!

The lib seems to use a function `styleInject` which injects some CSS into the document `head` using JS. This has presented a problem for me in two ways:

* It doesn't play well with web components, where the CSS should be injected into the shadow root rather than the document head
* It creates conflicts with existing styles. For example I have an existing CSS file that sets the Codemirror font, but then the library injects a `font-family: consolas !important` rule which wipes out my existing font settings.

I'd suggest allowing the user to add the Codemirror CSS themselves, rather than baking the CSS into the JS library, as this would improve flexibility of the library. Although even just removing the `!important` flags would be helpful.

### Validations

- [X] Read the [docs](https://renncheung.github.io/codemirror-editor-vue3/index.html).
- [X] Check that there isn't [already an issue](https://github.com/RennCheung/codemirror-editor-vue3/issues) that reports the same bug to avoid creating a duplicate.

**Comment by RennCheung** [comment]
Sorry, there is really a lack of considerations here. There are some styles of modifications in the single market. It is really necessary. This library already has a certain amount of download. It is not appropriate to delete the style of the automatic injection head.

Maybe I can provide a method or attribute to turn it off?In this way, you can still manually import style.

**Comment by Buroni** [comment]
Thanks for your reply @RennCheung. Yes, providing an option to turn off the automatic style injection would be great.

**Comment by RennCheung** [comment]
I am currently considering using the 'original-style' property to remove all style changes to 'CodeMirror' itself, but not to remove some style changes to the library, such as `width`, `height`, `border`, etc.,  example:
<img width="380" alt="image" src="https://user-images.githubusercontent.com/50518861/165458833-53bec7b4-4b5a-4d76-8e37-2c7c2f14e62f.png">

This is a code that is relatively small in existing code(The principle is controlled by CSS `:not` selector), and can control each component separately.

And I remove all `!Important`, if you have better suggestions to provide me, I will post a test version.

**Comment by RennCheung** [comment]
https://www.npmjs.com/package/codemirror-editor-vue3/v/2.1.0-beta

**Comment by Buroni** [comment]
Thanks @RennCheung that seems like a good solution
