### ISSUE TITLE
引入依赖报错

### ISSUE THREAD

**Issue by laowangdefangjian** [RennCheung/codemirror-editor-vue3#18]
### Describe the bug

<img width="434" alt="image" src="https://user-images.githubusercontent.com/30041340/165921804-54f036da-a541-4a69-a802-0109db774719.png">
在node_modules/codemirror/addon/merge/merge.js为引入diff_match_patch
请问如何解决？谢谢

### Validations

- [X] Read the [docs](https://renncheung.github.io/codemirror-editor-vue3/index.html).
- [X] Check that there isn't [already an issue](https://github.com/RennCheung/codemirror-editor-vue3/issues) that reports the same bug to avoid creating a duplicate.

**Comment by RennCheung** [comment]
codemirror的版本多少，尝试安装一下这个包看看能不能解决

最好提供一个可复现的demo

**Comment by laowangdefangjian** [comment]
版本号："codemirror-editor-vue3": "^2.0.6"
vue版本号："vue": "^3.2.13"

**Comment by laowangdefangjian** [comment]
您好，您的意思是用codemirror最新版，codemirror-editor-vue3这个包不建议使用吗

**Comment by laowangdefangjian** [comment]
您好，我换了codemirror最新版本，可以使用了，另外有一个源码的报错，我设置了markText的replacedWith之后，删除和获取焦点都报错Uncaught TypeError: Cannot read properties of undefined (reading 'map')，在(codemirror.js?0eda:2412:1)里，网上没有查到相关的错误信息，不知道是不是vue3导致的，如果您方便的话帮我解答一下，着急，谢谢

**Comment by laowangdefangjian** [comment]
您好，已解决，是vue3版本问题，在声明codeMirroi处加上vue3的markRaw，让数据不被追踪就不报错了，谢谢

**Comment by RennCheung** [comment]
> Reference in n

当然不是，这个包依赖于codemirror

**Comment by RennCheung** [comment]
你直接使用codemirror当然是可以的, 这个包只是基于codemirror做的二次封装

**Comment by laowangdefangjian** [comment]
那codemirror-editor-vue3这个包确实存在以上问题

**Comment by RennCheung** [comment]
请提供一个可复现此bug的demo，否则无法定位问题。

新建github仓库或者codesanbox都可以。
