### ISSUE TITLE
初始化不显示，也没有报错

### ISSUE THREAD

**Issue by xieqingchun** [RennCheung/codemirror-editor-vue3#2]
![image](https://user-images.githubusercontent.com/41767534/139616055-7d861666-8d33-4bca-8103-312bb40a49ec.png)

<template>
  <div class="codemirror-container">
    <div class="codemirror">
      <Codemirror
        v-model:value="reactData.code"
        :options="reactData.cmOptions"
        border
        placeholder="test placeholder"
        :height="240"
        @change="changeEvent"
      />
    </div>
    <pre class="pre">{{ reactData.code }}</pre>
  </div>
</template>

<script setup>
import Codemirror from 'codemirror-editor-vue3'
// plugin-style
import 'codemirror-editor-vue3/dist/style.css'
// language
import 'codemirror/mode/javascript/javascript.js'
// theme
// import 'codemirror/theme/dracula.css'
// theme css
import 'codemirror/theme/base16-light.css'
import { reactive, defineComponent, toRefs, getCurrentInstance, onMounted, onBeforeUnmount } from 'vue'

const reactData = reactive({
  cmOptions: {
    mode: 'text/javascript', // Language mode
    theme: 'base16-light', // Theme
    lineNumbers: true, // Show line number
    smartIndent: true, // Smart indent
    indentUnit: 2, // The smart indent unit is 2 spaces in length
    foldGutter: true, // Code folding
    styleActiveLine: true // Display the style of the selected row
  },
  code: `
var i = 0;
for (; i < 9; i++) {
  console.log(i);
  // more statements
}`
})

function changeEvent() {}
</script>
<style lang="scss" scoped>
.codemirror-container {
  display: flex;
  width: 100%;
  height: 100%;

  .codemirror,
  .pre {
    width: 50%;
    height: 100%;
    margin: 0;
    overflow: auto;
  }

  .pre {
    display: block;
    padding: 1rem;
    font-size: 14px;
    line-height: 1.6;
    word-break: break-all;
    word-wrap: break-word;
  }
}
</style>

**Comment by RennCheung** [comment]
我就直接中文回复了

我不能根据你的代码确定原因，但看样子你的业务有对codemirror 组件的隐藏显示操作，如果是这样，那么这个 bug 是来自  官方codemirror的问题，可以直接试一下官方的也有这个问题。

我的解决方案是在外层加一个 v-if, 用 settimeout 200ms就可以了。之后我在看看可不可以直接在codemirror-editor-vue3解决。

**Comment by xieqingchun** [comment]
> 我就直接中文回复了
> 
> 我不能根据你的代码确定原因，但看样子你的业务有对codemirror 组件的隐藏显示操作，如果是这样，那么这个 bug 是来自 官方codemirror的问题，可以直接试一下官方的也有这个问题。
> 
> 我的解决方案是在外层加一个 v-if, 用 settimeout 200ms就可以了。之后我在看看可不可以直接在codemirror-editor-vue3解决。

**Comment by xieqingchun** [comment]
好的，我试试

**Comment by xieqingchun** [comment]
是我这边隐藏的问题,我尝试修改一下
