### ISSUE TITLE
replaceSelection()  插入数据有具体的使用方式吗

### ISSUE THREAD

**Issue by nullnwk** [RennCheung/codemirror-editor-vue3#24]
### Describe the bug

replaceSelection()  插入数据有具体的使用方式吗

### Validations

- [X] Read the [docs](https://renncheung.github.io/codemirror-editor-vue3/index.html).
- [X] Check that there isn't [already an issue](https://github.com/RennCheung/codemirror-editor-vue3/issues) that reports the same bug to avoid creating a duplicate.

**Comment by RennCheung** [comment]
API problem please consult [codemirrror website](https://codemirror.net/5/doc/manual.html)

Provide a case：
```
      editor.addSelection({ line: 12, ch: 10 });
      editor.replaceSelection("test");
```

**Comment by nullnwk** [comment]
<Codemirror v-model:value="cm.code" :options="cm.options" border placeholder="test placeholder" :height="125" @change="change" />
 以这种方式定义的，deitor怎么拿到啊，麻烦帮忙解答一下

**Comment by RennCheung** [comment]
https://renncheung.github.io/codemirror-editor-vue3/instructions/cminstance.html

**Comment by nullnwk** [comment]
感谢
