### ISSUE TITLE
请问大佬vue的模板如何支持语法高亮，现在的语言包语法高亮总是不对

### ISSUE THREAD

**Issue by yixinagqingyuan** [RennCheung/codemirror-editor-vue3#25]
### Describe the bug

如图所示语法高亮有问题
![image](https://user-images.githubusercontent.com/31228587/178952496-72c5f342-d788-4e2c-85b0-86299ac7653f.png)

 但是别人的语法高亮没问题 

https://codepen.io/ouhsnaux/pen/oNqzjKW

### Validations

- [X] Read the [docs](https://renncheung.github.io/codemirror-editor-vue3/index.html).
- [X] Check that there isn't [already an issue](https://github.com/RennCheung/codemirror-editor-vue3/issues) that reports the same bug to avoid creating a duplicate.

**Comment by RennCheung** [comment]
高亮受主题影响，可以切换主题查看效果

**Comment by yixinagqingyuan** [comment]
我用的是6.0版本，没有官方包，没辙了，给他们html 的语言包拔下来，改了改，哎

**Comment by RennCheung** [comment]
这个库使用的是5.x 版本
