### ISSUE TITLE
when delete all code, change emits not correct, 

### ISSUE THREAD

**Issue by OrangeCat3** [RennCheung/codemirror-editor-vue3#30]
### Describe the bug

<img width="1703" alt="image" src="https://user-images.githubusercontent.com/30597850/208079372-62805cf4-2506-496e-b76d-e7185a834822.png">

### Validations

- [X] Read the [docs](https://renncheung.github.io/codemirror-editor-vue3/index.html).
- [X] Check that there isn't [already an issue](https://github.com/RennCheung/codemirror-editor-vue3/issues) that reports the same bug to avoid creating a duplicate.

**Comment by iyjian** [comment]
https://codesandbox.io/s/admiring-scooby-yub8zg?file=/src/App.vue

**Comment by iyjian** [comment]
@RennCheung  the above is reproduce code

1. select all code text in editor use ctrl + A 
2. enter "delete" button

the data.code won't change, you can see the text under the editor box.

**Comment by RennCheung** [comment]
The issue has been resolved. Please upgrade to the latest version

**Comment by iyjian** [comment]
thankyou
