### ISSUE TITLE
 Can't resolve 'codemirror/mode/javascript/javascript.js'

### ISSUE THREAD

**Issue by zhouyaxi** [RennCheung/codemirror-editor-vue3#31]
### Describe the bug

It can`t work correctly.
![image](https://user-images.githubusercontent.com/45450557/209550029-a3c62048-ad99-41ff-8b34-4da2db4f07da.png)

![image](https://user-images.githubusercontent.com/45450557/209549916-c0230fd5-585f-4b8e-aad0-6a397d3ecc22.png)

![image](https://user-images.githubusercontent.com/45450557/209549809-5938b044-15f1-4e60-b7db-ca65e12f156d.png)

### Validations

- [X] Read the [docs](https://renncheung.github.io/codemirror-editor-vue3/index.html).
- [X] Check that there isn't [already an issue](https://github.com/RennCheung/codemirror-editor-vue3/issues) that reports the same bug to avoid creating a duplicate.

**Comment by RennCheung** [comment]
You also need to install separately 5.x version of Codemirror dependencies
