### ISSUE TITLE
火狐浏览器兼容问题

### ISSUE THREAD

**Issue by zhangluqi7** [RennCheung/codemirror-editor-vue3#32]
### Describe the bug

当页面出现滚动 编辑器种也有滚动时候
火狐会变卡，并且控制台出现警告

只有火狐出现
火狐的警告：
此网站似乎使用 scroll-linked 定位效果。这可能无法与异步平移一起使用；参见 https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects 详细了解，也可加入我们一起讨论相关的工具和功能！

火狐版本：63.0.3 (64 位)

### Validations

- [X] Read the [docs](https://renncheung.github.io/codemirror-editor-vue3/index.html).
- [X] Check that there isn't [already an issue](https://github.com/RennCheung/codemirror-editor-vue3/issues) that reports the same bug to avoid creating a duplicate.

**Comment by RennCheung** [comment]
抱歉，我无法复现你的问题，我使用 mac电脑，并且你是用的 firefox 版本较老，无法确定问题出自哪里
