### ISSUE TITLE
关于placeholder失效问题

### ISSUE THREAD

**Issue by kid1110** [RennCheung/codemirror-editor-vue3#33]
### Describe the bug
当我按照useage使用 placeholder参数时，输入框并没有显示相关placeholder

### 解决方法：
引入以下文件
`<script>
    import "codemirror/addon/display/placeholder.js"
</script>`
麻烦更新一下useage的readme文件

### Validations

- [x]  Read the [docs](https://renncheung.github.io/codemirror-editor-vue3/index.html).
- [x] Check that there isn't [already an issue](https://github.com/RennCheung/codemirror-editor-vue3/issues) that reports the same bug to avoid creating a duplicate.

**Comment by RennCheung** [comment]
已补充
