### ISSUE TITLE
根据示例编引入组件提示Missing "./mode/javascript/javascript.js" export in "codemirror" package

### ISSUE THREAD

**Issue by AnimalWorld-zhongxiangzhao** [RennCheung/codemirror-editor-vue3#35]
### Describe the bug

[vite] Internal server error: Missing "./mode/javascript/javascript.js" export in "codemirror" package

### Validations

- [X] Read the [docs](https://renncheung.github.io/codemirror-editor-vue3/index.html).
- [X] Check that there isn't [already an issue](https://github.com/RennCheung/codemirror-editor-vue3/issues) that reports the same bug to avoid creating a duplicate.

**Comment by RennCheung** [comment]
```
npm i codemirror@5.6.0
```

之后再更新一下文档

**Comment by AnimalWorld-zhongxiangzhao** [comment]
谢谢

**Comment by liurich12138** [comment]
解决了吗大佬 为什么我更新完了还是报这个错

**Comment by rennzhang** [comment]
> 解决了吗大佬 为什么我更新完了还是报这个错

是不是没有安装 `@types/codemirror`

**Comment by AnimalWorld-zhongxiangzhao** [comment]
> 解决了吗大佬 为什么我更新完了还是报这个错

根据作者提供操作解决了。
