### ISSUE TITLE
编辑器代码内容无法高亮,已引入相关js

### ISSUE THREAD

**Issue by AnimalWorld-zhongxiangzhao** [RennCheung/codemirror-editor-vue3#36]
### Describe the bug

请问是哪里出现了问题谢谢,浏览器没有报错信息
<img width="620" alt="image" src="https://user-images.githubusercontent.com/19886578/222397465-c73e8b01-53e1-43ba-9652-2cb6d78af591.png">
<img width="828" alt="image" src="https://user-images.githubusercontent.com/19886578/222398542-56f8a4f6-e00d-4595-9c85-5750dafddedb.png">
<img width="582" alt="image" src="https://user-images.githubusercontent.com/19886578/222398398-6affcf23-fefa-44b4-8cdc-e53799515ca1.png">

### Validations

- [X] Read the [docs](https://renncheung.github.io/codemirror-editor-vue3/index.html).
- [X] Check that there isn't [already an issue](https://github.com/RennCheung/codemirror-editor-vue3/issues) that reports the same bug to avoid creating a duplicate.

**Comment by RennCheung** [comment]
这个代码看不来问题，最好提供一份能复现的代码

**Comment by AnimalWorld-zhongxiangzhao** [comment]
我按照示例代码写了个简单的页面也依旧无法显示高亮
<img width="1190" alt="image" src="https://user-images.githubusercontent.com/19886578/223056999-04052399-433a-4540-b1df-124917ef643f.png">
<img width="1369" alt="image" src="https://user-images.githubusercontent.com/19886578/223057080-eee1a190-395b-42e0-a786-aec8188609d4.png">

**Comment by RennCheung** [comment]
不好意思，是我升级了 vite 后产生的一些问题，如果着急请先试用2.2.0以下的版本

**Comment by RennCheung** [comment]
现在你可以升级到最新版使用了，之前是因为文档更新出现纰漏，codemirror 的版本过低导致的问题。

文档已经更新也修改了一些细节，可以参考文档的案例了。

**Comment by AnimalWorld-zhongxiangzhao** [comment]
> 现在你可以升级到最新版使用了，之前是因为文档更新出现纰漏，codemirror 的版本过低导致的问题。
> 
> 文档已经更新也修改了一些细节，可以参考文档的案例了。

谢谢
