### ISSUE TITLE
Focus the editor

### ISSUE THREAD

**Issue by hudec117** [RennCheung/codemirror-editor-vue3#39]
**Is your feature request related to a problem? Please describe.**
I would like to be able to focus the Codemirror editor.

**Describe the solution you'd like**
Focus the editor using a .focus() like call. Or access to the underlying Codemirror instance to be able to call any documented functions.

**Comment by RennCheung** [comment]
I am not quite grasping the essence of your message. If you wish to bring focus to an editing box, you may use the following approach. Please refer to the documentation for details：https://renncheung.github.io/codemirror-editor-vue3/zh-CN/supplementary/instance

<img width="840" alt="image" src="https://github.com/RennCheung/codemirror-editor-vue3/assets/50518861/f9b08478-3181-4e0a-a23d-8783240bb9a8">
<img width="899" alt="image" src="https://github.com/RennCheung/codemirror-editor-vue3/assets/50518861/58c75a12-b1c2-48c2-a2ad-8ea12ab9fc72">

**Comment by hudec117** [comment]
That's what I'm looking for! Thanks
