### ISSUE TITLE
how to use addWidget ?

### ISSUE THREAD

**Issue by zerocsss** [RennCheung/codemirror-editor-vue3#4]
how to get an instance

cm.addWidget(pos: {line, ch}, node: Element, scrollIntoView: boolean)
Puts node, which should be an absolutely positioned DOM node, into the editor, positioned right below the given {line, ch} position. When scrollIntoView is true, the editor will ensure that the entire node is visible (if possible). To remove the widget again, simply use DOM methods (move it somewhere else, or call removeChild on its parent).

**Comment by RennCheung** [comment]
Do you read the documentation carefully?
![image](https://user-images.githubusercontent.com/50518861/140872211-e65c2e54-006b-4a3b-b7af-18c67489e344.png)
In addition, it can be obtained by ref.

**Comment by zerocsss** [comment]
OK, thanks
