### ISSUE TITLE
Unable to preventDefault inside passive event listener invocation.

### ISSUE THREAD

**Issue by xieqingchun** [RennCheung/codemirror-editor-vue3#5]
![image](https://user-images.githubusercontent.com/41767534/143671349-9428abd8-c0e0-438d-a333-e7386c9b61b5.png)
选中会报错

**Comment by RennCheung** [comment]
Please provide a complete code example, I can't guess your problem how to appear.🙃

**Comment by topcloud-xx** [comment]
看看是不是引用default-passive-events组件
引用了这个会出现所说的问题
