### ISSUE TITLE
Is Autocomplete possible with this library?

### ISSUE THREAD

**Issue by tpoxa** [RennCheung/codemirror-editor-vue3#7]
Here is the official demo:

https://codemirror.net/demo/complete.html
Thanks.

**Comment by RennCheung** [comment]
I don't understand how this case is used.

I used Chrome in the demo you provided and hit Ctrl-Space and got no response

**Comment by tpoxa** [comment]
Oh, sorry, please try this example instead 

https://codemirror.net/6/examples/autocompletion/

**Comment by RennCheung** [comment]
Sorry, I have no time to try this feature in the near future, and the Demo version number you provide is 6, this library relies on the version of 5.x.

In theory, this library does not affect the features that CODEMIRROR can support. Do you use this library to try AutoComplete related features?If you have any questions using this feature, you can feed back me again.

**Comment by RennCheung** [comment]
https://github.com/RennCheung/codemirror-editor-vue3/issues/12
