### ISSUE TITLE
按教程设置后，代码内容无法高亮，但是我看你的博客里的demo，好像是可以高亮的

### ISSUE THREAD

**Issue by CedarXi** [RennCheung/codemirror-editor-vue3#8]

**Comment by RennCheung** [comment]
看一下你的完整代码

**Comment by CedarXi** [comment]
> 看一下你的完整代码

`<template>
  <div class="codeBlockEditor">
    <a-collapse>
      <a-collapse-item header="Beijing Toutiao Technology Co., Ltd.">
        <Codemirror
          v-model:value="code"
          :options="cmOptions"
          border
          placeholder="测试 placeholder"
          :height="200"
          @change="onChange"
        />
      </a-collapse-item>
    </a-collapse>
  </div>
</template>

<script>
import Codemirror from "codemirror-editor-vue3";

const code = ``;
export default {
  components: {
    Codemirror,
  },
  data() {
    return {
      code,
      cmOptions: {
        mode: "text/javascript", // 语言模式
        theme: "default", // 主题
        lineNumbers: true, // 显示行号
        smartIndent: true, // 智能缩进
        indentUnit: 2, // 智能缩进单位为4个空格长度
        foldGutter: true, // 启用行槽中的代码折叠
        styleActiveLine: true, // 显示选中行的样式
      },
    };
  },
  methods: {
    onChange(val, cm) {},
  },
  created() {
    // console.log('111')
  },
};
</script>

<style lang="less">
.codeBlockEditor {
  .arco-collapse-item-content {
    padding: 0;
    height: 200px !important;
    .arco-collapse-item-content-box {
      padding: 0;
      .arco-textarea-wrapper {
        background: var(--color-fill-1);
        border: none;
      }
    }
    .codemirror-container{
      border: none;
      cursor: text; 
    }
  }
}
</style>`

这个是页面的图片
![image](https://user-images.githubusercontent.com/16424854/149618831-017653d4-e21a-4aed-ba5e-77f0c413593f.png)

**Comment by RennCheung** [comment]
你没有引入语言包
// language
import "codemirror/mode/javascript/javascript.js";

**Comment by CedarXi** [comment]
> 你没有引入语言包 // language import "codemirror/mode/javascript/javascript.js";

哦 哦，抱歉啊，没仔细看案例，注意到
